#!/bin/bash

## Description: Clone and install UI Patterns
## Usage: enable
## Example: "ddev enable"

# Abort if anything fails
set -e

drush en ui_patterns ui_patterns_blocks ui_patterns_field_formatters ui_patterns_layouts ui_patterns_views ui_patterns_library ui_skins
