#!/bin/bash

## Description: Clone and install UI Patterns
## Usage: init
## Example: "ddev init"

# Abort if anything fails
set -e

echo "composer install"
composer install

ROOT="/var/www/html"
CUSTOM_FOLDER="web/modules/custom"

mkdir -p $CUSTOM_FOLDER
if [ ! -d "$CUSTOM_FOLDER/ui_patterns" ]; then
  cd $CUSTOM_FOLDER
  git clone https://git.drupalcode.org/project/ui_patterns.git
  cd ui_patterns
  git checkout 2.0.x
fi
cd $ROOT
drush si -y
drush en ui_patterns ui_patterns_blocks ui_patterns_field_formatters ui_patterns_layouts ui_patterns_views -y
drush cr
