#!/bin/bash

## Description: Run phpcbf
## Usage: phpcbf
## Example: "ddev phpcbf"

# Abort if anything fails
set -e
phpcbf --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md,yml /var/www/html/web/modules/custom/ui_patterns